trigger:
- 'master'

stages:
- stage: 'Build'
  displayName: 'Build and push'
  jobs:  
  - job: 'Build'
    displayName: 'Build job'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: CmdLine@2
      inputs:
        script: 'git clone https://github.com/iam-aravind/mslearn-tailspin-spacegame-web-kubernetes.git'
    - task: oc-cmd@3
      inputs:
        connectionType: 'OpenShift Connection Service'
        openshiftService: 'openshift-3'
        cmd: 'oc login --token=sha256~yFvdvdA9HHbtDgjPwV3ka8yzDnxRwXWqAlEbuvPEgZU --server=https://api.sandbox-m2.ll9k.p1.openshiftapps.com:6443'
    - task: oc-cmd@3
      inputs:
        connectionType: 'OpenShift Connection Service'
        openshiftService: 'openshift-3'
        cmd: 'oc apply -f deployment.yml'
